"""added last fetched at product table

Revision ID: 5b1e4b299eeb
Revises: 1770768a4c95
Create Date: 2025-12-23 20:03:25.720661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1e4b299eeb'
down_revision = '1770768a4c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fetched_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('last_fetched_at')

    # ### end Alembic commands ###
